notify-update: true
worlds:
  # which worlds are allowed to carry
  - world
  - world_nether
  - world_the_end
  - test
spawn-egg-lore: '&9Name:&f {entity}'
item:
  type: LEAD
  enchantment: none
entity:
  ALLAY: true
  ARMADILLO: true
  AXOLOTL: false
  BAT: false
  BEE: true
  BLAZE: false
  BOGGED: false
  BREEZE: false
  CAMEL: false
  CAT: true
  CAVE_SPIDER: false
  CHICKEN: true
  COD: false
  COPPER_GOLEM: true
  COW: true
  CREEPER: false
  DOLPHIN: true
  DONKEY: true
  DROWNED: false
  ENDER_DRAGON: false
  ENDERMAN: false
  ENDERMITE: true
  EVOKER: false
  FOX: true
  FROG: true
  GHAST: false
  GIANT: false
  GOAT: true
  GUARDIAN: false
  HAPPY_GHAST: false
  HOGLIN: false
  HORSE: true
  HUSK: false
  ILLUSIONER: false
  IRON_GOLEM: true
  LLAMA: true
  MOOSHROOM: true
  MULE: true
  OCELOT: true
  PANDA: true
  PARROT: true
  PHANTOM: false
  PIG: true
  PIGLIN: true
  PIGLIN_BRUTE: false
  PILLAGER: false
  POLAR_BEAR: false
  PUFFERFISH: false
  RABBIT: true
  RAVAGER: false
  SALMON: false
  SHEEP: true
  SHULKER: false
  SILVERFISH: true
  SKELETON: false
  SKELETON_HORSE: true
  SNIFFER: true
  SNOW_GOLEM: true
  SPIDER: false
  SQUID: true
  STRAY: false
  STRIDER: true
  TADPOLE: false
  TRADER_LLAMA: true
  TROPICAL_FISH: false
  TURTLE: true
  VEX: false
  VILLAGER: true
  VINDICATOR: false
  WANDERING_TRADER: true
  WARDEN: false
  WITCH: false
  WITHER: false
  WITHER_SKELETON: false
  WOLF: true
  ZOGLIN: false
  ZOMBIE: false
  ZOMBIE_HORSE: true
  ZOMBIE_VILLAGER: true
  ZOMBIFIED_PIGLIN: true
